Formatting the linting output
Instagram/Fixit pull request #257
Opened 2023-02-08 00:06 UTC by Chenguang-Zhu

## Summary
Currently, Fixit just dumps objects to stdout. This pull request changes the output  to this format: `<filepath>@<line>:<col> <rulename>: <summary>`. It also colors the output in red. 

## Test Plan
`make test lint html` should give no errors. 
Run `hatch env run -- fixit lint .` in the Fixit root directory, the new output format is as follows:
<img width="1132" alt="Screenshot 2023-02-07 at 4 05 12 PM" src="https://user-images.githubusercontent.com/19936324/217395061-1c62c3d8-636d-448a-9b3d-8e9ec7e6d97a.png">

2023-02-08 19:56 UTC, amyreese requested changes
Just needs to handle the case where `error` is set, eg, when an exception occurred while processing a file. The `error` attribute contains both the exception object and a string containing the traceback information. In the normal case, I think we would skip the traceback, and maybe only print it if the `--debug` flag has been passed. Also, I think it could make sense to have normal lint violations print in yellow, but errors print in red.

I think it might be better to make the `__str__` method a separate `print_result` function that takes a `Result` object and returns a string. That would not only allow for passing an alternative (eg `json_result`) but would also allow passing options like the `--debug` flag mentioned above.

2023-02-09 01:58 UTC, Chenguang-Zhu commented
Hi @amyreese , I updated the code to handle error cases. Now the violations are in the following format:
<img width="1398" alt="Screenshot 2023-02-08 at 5 53 59 PM" src="https://user-images.githubusercontent.com/19936324/217696758-c3c17d96-8a68-4a55-80f8-2dfd7c05fd8c.png">

When the file has errors, without `--debug`:
<img width="843" alt="Screenshot 2023-02-08 at 5 55 11 PM" src="https://user-images.githubusercontent.com/19936324/217696925-bcc28192-edaa-4d04-8279-8453c59d1a3c.png">

With `--debug`:
<img width="843" alt="Screenshot 2023-02-08 at 5 58 23 PM" src="https://user-images.githubusercontent.com/19936324/217697435-342879b3-b024-45cd-8ba9-a5dc0602e106.png">

2023-02-09 21:51 UTC, amyreese approved these changes
Overall looks good. Just have a few outstanding nits left before we can merge this. Cheers!

2023-02-09 21:51 UTC, amyreese commented on src/fixit/api.py
> +        if result.error:
Better to combine this into a single `elif` rather than nesting.

2023-02-09 21:51 UTC, amyreese commented on src/fixit/api.py
> +            traceback_info = result.error[1]
Prefer simple unpacking, like:

    error, tb = result.error

2023-02-09 21:51 UTC, amyreese commented on src/fixit/api.py
> +def print_result(result: Result, debug: bool) -> None:
Set a default value for `debug = False`, to make this a nicer API for external usage.

Would also appreciate a docstring here, and add it to the "simple API" sections of the sphinx docs (see `docs/api.rst`).

2023-02-10 00:04 UTC, merged