Skip files if no rules are enabled
Instagram/Fixit pull request #379
Opened 2023-08-15 08:42 UTC by datur

## Summary

To avoid unnecessary processing of files if no rules are enabled for a given file the config is now checked before processing a file and if no rules are enabled the file is skipped.

## Test Plan

2023-08-16 23:00 UTC, amyreese requested changes
There are two main issues with this approach:

1) by skipping the call to `fixit_bytes()`, we are not generating a clean `Result()` object for the file, which will result in the CLI output under-counting the number of clean file results.

2) this only catching cases where the *file config* has no enabled rules/modules, but doesn't prevent visiting files when the number of rules actually discovered at runtime is empty (eg, passing `--tags` to CLI or combination of enable/disable that results in no selected rules).

I think the better solution is to modify `fixit_bytes()` instead such that it generates a clean result and aborts early if the result of `collect_rules(...)` is empty.

2023-08-17 08:42 UTC, datur commented
Thanks for the review @amyreese I believe I have addressed your change requests now! Let me know if you have any other feedback 😄

2023-08-22 01:44 UTC, amyreese approved these changes

2023-08-22 01:49 UTC, merged

2023-08-22 01:49 UTC, amyreese commented
Thank you!