feat: support `cat foo.py | fixit lint --stdin --stdin-filepath foo.py`
Instagram/Fixit pull request #388
Opened 2023-09-06 14:11 UTC by llllvvuu

Similarly for `fixit fix`

## Summary
Related to #122 but does not fully resolve it. It supports a lint-as-you-type workflow, whereas only a lint-on-save workflow could be supported before. Full resolution of #122 would require #387.

## Test Plan
Extended smoke tests.

2023-09-06 14:15 UTC, llllvvuu commented
CLA submitted

2023-09-27 23:53 UTC, amyreese requested changes
I like this as functionality to support, but I'd rather push this functionality into the supported API, rather than handling stdin at the CLI layer.

Take a look at how we did this for µfmt, where passing `Path("-")` (what you get from click.Path(allow_dash=True) as the first element of `paths` to `ufmt_paths(...)` triggers handling for stdin.

Adding `fixit_stdin` to the API to handle reading stdin and wrap `fixit_bytes` would be the first step, then update `fixit_paths` to detect the stdin sentinel and defer to `fixit_stdin` instead of normal file processing.

Is that something you would be interested in tackling, or would you rather I adapt your work accordingly?

2023-09-27 23:56 UTC, llllvvuu commented
Just took a look at ufmt CLI and happy to make the changes. Would we still need `--stdin-filepath`? (for `generate_config`)

Like:
```sh
fixit lint - --stdin-filepath foo.py
```

2023-09-28 00:22 UTC, amyreese commented
> Just took a look at ufmt CLI and happy to make the changes. So to confirm, intended usage is
> 
> ```shell
> fixit lint - path/to/foo.py  # formats stdin, treating it as if it is located at path/to/foo.py
> ```

Correct :)

2023-09-30 09:01 UTC, llllvvuu commented
Just made the changes, thanks again for the ufmt reference!

I wasn't able to leave `cli.py` 100% unchanged since `fixit fix` needs to disable `--interactive` (as STDIN is occupied) and redirect `Result`s to STDERR (as STDOUT is occupied). But let me know what you think

2023-10-25 01:20 UTC, merged

2023-10-25 01:20 UTC, amyreese commented
Thank you!